name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install flake8 pylint bandit mypy
      - name: Run flake8
        run: flake8 .
      - name: Run pylint
        run: pylint Apps/
      - name: Run bandit
        run: bandit -r Apps/
      - name: Run mypy
        run: mypy Apps/